# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
       # Requirements for NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-nose
    - python-tables 
    - python-all-dev
    - libreadline-dev 
    - libncurses-dev 
    - libboost-python-dev
    - libltdl-dev
    - libgsl-dev
    - cython
    - openmpi-bin 
    - libopenmpi-dev
   


language: python

python: 
  - "2.7"
  - "3.6" 
  

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyNEST
    - OMV_ENGINE=NEST

install: 
    
    - pip install scipy matplotlib # Why is this needed? Doesn't seem to get installed correctly with addons above...
    
    # Install OMV

    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv list-engines -V
    
    - omv all -V
    
    - export JNML_HOME=/home/travis/jnml/jNeuroMLJar
    - export PATH=$PATH:$JNML_HOME
    - if [[ ${OMV_ENGINE} == "jNeuroML" ]]; then ./regenerate.sh ; fi
    
    # Set NEST variables
    - if [[ ${OMV_ENGINE} == *"NEST"* ]]; then source $TRAVIS_HOME/nest/nest/bin/nest_vars.sh; which nest ; fi
    
    - omv list-engines -V
    - env
    
    
    
    

