# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false

addons:
  apt:
    packages:
       # Requirements for NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    - python-tables 
    - python-tk
    - python-tornado
    - libreadline6-dev 
    - libncurses5-dev 
    - libgsl0-dev
    - cython


language: python

python: 
  - "2.7"
  - "3.6" 
  - "3.7" 
  



env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=PyNEST:2.18.0

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - export JNML_HOME=/home/travis/jnml/jNeuroMLJar
    - export PATH=$PATH:$JNML_HOME
    - if [[ ${OMV_ENGINE} == "jNeuroML" ]]; then ./regenerate.sh ; fi
    
    
    # Set NEST variables
    - if [[ ${OMV_ENGINE} == "PyNEST" ]]; then source $TRAVIS_HOME/nest/nest/bin/nest_vars.sh ; fi
    
    - omv list-engines -V
    - env
    
    
    
    

